#blue
version: '3'
services:
  cogito-api:
    build: .
    ports:
      - "8081:8080"
    container_name: spring-blue

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot_blue
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6380:6379