#green
version: '3'
services:
  cogito-api:
    build: .
    ports:
      - "8082:8080"
    container_name: spring-green

  redisdb:
    image: redis
    restart: always
    ports:
      - 6379:6379
    container_name: cogito-redis
    volumes:
      - redisdb:/var/lib/redis